import random


CHARACTERS = [
    {
        "id": 1,
        "nombre": "Ana",
        "avatar": "A",
        "genero": "femenino",
        "gafas": True,
        "sombrero": False,
        "barba": False,
        "bigote": False,
        "cabello_largo": True,
        "color_cabello": "negro",
        "accesorio": "aretes",
    },
    {
        "id": 2,
        "nombre": "Bruno",
        "avatar": "B",
        "genero": "masculino",
        "gafas": False,
        "sombrero": True,
        "barba": True,
        "bigote": True,
        "cabello_largo": False,
        "color_cabello": "castano",
        "accesorio": "bufanda",
    },
    {
        "id": 3,
        "nombre": "Carla",
        "avatar": "C",
        "genero": "femenino",
        "gafas": False,
        "sombrero": False,
        "barba": False,
        "bigote": False,
        "cabello_largo": True,
        "color_cabello": "rubio",
        "accesorio": "collar",
    },
    {
        "id": 4,
        "nombre": "Diego",
        "avatar": "D",
        "genero": "masculino",
        "gafas": True,
        "sombrero": False,
        "barba": False,
        "bigote": True,
        "cabello_largo": False,
        "color_cabello": "rojo",
        "accesorio": "corbata",
    },
    {
        "id": 5,
        "nombre": "Elena",
        "avatar": "E",
        "genero": "femenino",
        "gafas": True,
        "sombrero": True,
        "barba": False,
        "bigote": False,
        "cabello_largo": False,
        "color_cabello": "gris",
        "accesorio": "broche",
    },
    {
        "id": 6,
        "nombre": "Felipe",
        "avatar": "F",
        "genero": "masculino",
        "gafas": False,
        "sombrero": False,
        "barba": True,
        "bigote": False,
        "cabello_largo": True,
        "color_cabello": "negro",
        "accesorio": "audifonos",
    },
    {
        "id": 7,
        "nombre": "Gabriela",
        "avatar": "G",
        "genero": "femenino",
        "gafas": False,
        "sombrero": True,
        "barba": False,
        "bigote": False,
        "cabello_largo": True,
        "color_cabello": "castano",
        "accesorio": "lazo",
    },
    {
        "id": 8,
        "nombre": "Hector",
        "avatar": "H",
        "genero": "masculino",
        "gafas": True,
        "sombrero": True,
        "barba": False,
        "bigote": False,
        "cabello_largo": False,
        "color_cabello": "rubio",
        "accesorio": "reloj",
    },
    {
        "id": 9,
        "nombre": "Isabel",
        "avatar": "I",
        "genero": "femenino",
        "gafas": False,
        "sombrero": False,
        "barba": False,
        "bigote": False,
        "cabello_largo": False,
        "color_cabello": "rojo",
        "accesorio": "pulsera",
    },
    {
        "id": 10,
        "nombre": "Jorge",
        "avatar": "J",
        "genero": "masculino",
        "gafas": False,
        "sombrero": False,
        "barba": True,
        "bigote": True,
        "cabello_largo": False,
        "color_cabello": "gris",
        "accesorio": "panuelo",
    },
    {
        "id": 11,
        "nombre": "Laura",
        "avatar": "L",
        "genero": "femenino",
        "gafas": True,
        "sombrero": False,
        "barba": False,
        "bigote": False,
        "cabello_largo": True,
        "color_cabello": "castano",
        "accesorio": "diadema",
    },
    {
        "id": 12,
        "nombre": "Mateo",
        "avatar": "M",
        "genero": "masculino",
        "gafas": False,
        "sombrero": True,
        "barba": False,
        "bigote": True,
        "cabello_largo": True,
        "color_cabello": "negro",
        "accesorio": "mochila",
    },
    {
        "id": 13,
        "nombre": "Natalia",
        "avatar": "N",
        "genero": "femenino",
        "gafas": True,
        "sombrero": True,
        "barba": False,
        "bigote": False,
        "cabello_largo": False,
        "color_cabello": "rubio",
        "accesorio": "flor",
    },
    {
        "id": 14,
        "nombre": "Oscar",
        "avatar": "O",
        "genero": "masculino",
        "gafas": True,
        "sombrero": False,
        "barba": True,
        "bigote": False,
        "cabello_largo": False,
        "color_cabello": "castano",
        "accesorio": "chaleco",
    },
    {
        "id": 15,
        "nombre": "Paula",
        "avatar": "P",
        "genero": "femenino",
        "gafas": False,
        "sombrero": True,
        "barba": False,
        "bigote": False,
        "cabello_largo": True,
        "color_cabello": "gris",
        "accesorio": "bolso",
    },
    {
        "id": 16,
        "nombre": "Rafael",
        "avatar": "R",
        "genero": "masculino",
        "gafas": True,
        "sombrero": False,
        "barba": False,
        "bigote": True,
        "cabello_largo": False,
        "color_cabello": "rojo",
        "accesorio": "camara",
    },
]


def get_random_board():
    board = CHARACTERS.copy()
    random.shuffle(board)
    return board
